update SDK documentation page -> options watch en vagrant removed
in short : options watch en vagrant seem to have been removed : https://github.com/liquibase/liquibase/commit/b2b879cab8581f568868a693c2bf7b15c1311614#diff-6cc73ec775a2dcf7cf5de9aa4831d474

I first got error 
λ liquibase-sdk watch --url=jdbc\:oracle\:thin\:@//oradevp03.ugent.be:1521/DEVGISMO --username=NICPERSY --password=NICPERSY
Error: Unable to initialize main class liquibase.sdk.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser

after adding the jar commons-cli-1.4.jar manually to lib-sdk, I got 
---------------------------------------------------
ERROR EXECUTING COMMAND
---------------------------------------------------
Unknown command: watch

after reviewing Main.java history, I saw that it was removed from the source
https://github.com/liquibase/liquibase/commits/master/liquibase-core/src/main/java/liquibase/sdk/Main.java


Kind Regards, 
Nick